/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2016-12-22 09:09:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import model.Articolo;
import model.TShirt;
import model.Cart;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.TShirt");
    _jspx_imports_classes.add("model.Articolo");
    _jspx_imports_classes.add("model.Cart");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 Collection<?> productsM = (Collection<?>) request.getAttribute("productsM");
   Articolo product = (Articolo) request.getAttribute("product"); 
   Cart cart = (Cart) request.getAttribute("cart");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <link rel=\"icon\" href=\"Immagini/sprite0.png\" />\r\n");
      out.write("    <script src=\"Script/jquery.js\"></script>\r\n");
      out.write("    <script src=\"Script/update.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/base.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/Cart.css\" type=\"text/css\">\r\n");
      out.write("    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"Content-Language\" content=\"it-IT\" />\r\n");
      out.write("    <meta name=\"description\" content=\"Il miglior sito dove acquistare T-Shirt  per qualsiasi gusto e necessità, con un'ampia scelta di modelli aggiornati periodicamente con i migliori design della rete.\" />\r\n");
      out.write("    <meta name=\"keywords\" content=\"T-shirt, magliette, maglietta, nerd, cinema, divertenti, geek, core, series, best\" />\r\n");
      out.write("    <title>Core Shirt: The Best T-Shirts series</title>\r\n");
      out.write("    </head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("    <article id=\"articolo1\">\r\n");
      out.write("    <div id=\"lista\">\r\n");
      out.write("    <a href=\"./\"><div id=\"banner\"> <img class=\"Banner\" src=\"Immagini/prova.png\"> \r\n");
      out.write("          <img class=\"core\" src=\"Immagini/core2.png\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    <div>\r\n");
      out.write("    <nav>    \r\n");
      out.write("        <ul id=\"menu\">\r\n");
      out.write("            <li><a href=\"./\"><img class=\"home\" src=\"Immagini/home.png\"></a> </li>\r\n");
      out.write("            <li><a href=\"./?action=Uomo\"> Uomo </a></li>\r\n");
      out.write("            <li><a href=\"./?action=Donna\"> Donna  </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"./About\">About</a></li>\r\n");
      out.write("            <li><a href=\"./Help\">Help</a></li>   \r\n");
      out.write("            <li><a href=\"./Checkout\">Checkout</a></li>\r\n");
      out.write("            <li><a href=\"./?action=cart\">\r\n");
      out.write("                <img class=\"cart\" src=\"Immagini/cart.png\"></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </article>\r\n");
      out.write("    <!-- </div>-->\r\n");
      out.write("         <article>\r\n");
      out.write("    <aside id=\"aside_bar\">\r\n");
      out.write("        <span> <img src=\"Immagini/spedizione.png\"> \r\n");
      out.write("            <div class=\"promesse\">\r\n");
      out.write("                Spedizione gratuita dopo i 3 articoli</div></span>\r\n");
      out.write("        <span class=\"48h\"><img src=\"Immagini/48h.png\">\r\n");
      out.write("            <div class=\"promesse\">Spedizione in 48 ore con corriere espresso</div>\r\n");
      out.write("        </span>\r\n");
      out.write("        \r\n");
      out.write("            <!--<div class=\"spedizione1\">-->\r\n");
      out.write("                \r\n");
      out.write("        <span class=\"48h\"><img src= \"Immagini/Soddisfazione.png\">\r\n");
      out.write("            <div class=\"promesse\">Soddisfatti al 100%</div>\r\n");
      out.write("        </span>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        </aside>\r\n");
      out.write("    \r\n");
      out.write("    </article>\r\n");
      out.write("\r\n");
      out.write("<div id=\"contenitore\">\r\n");
      out.write(" ");
 String x=""+cart.getTotal();
    x=x.substring(0,x.length()-2);
     if(cart != null) { 
      out.write("\r\n");
      out.write("\t\t<h2 class=\"minghie\">Carrello</h2>\r\n");
      out.write("\t\t<table class=\"tabella\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t<th>Color</th>\r\n");
      out.write("\t\t\t<th>Size</th>\r\n");
      out.write("\t\t\t<th>Quantity</th>\r\n");
      out.write("\t\t\t<th>Price</th>\r\n");
      out.write("\t\t\t<th>Action</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
 ArrayList<TShirt> prodcart = cart.getProducts(); 
		   int k=0;
		   for(TShirt beancart: prodcart) {
			   k++;
			   String path="./Immagini/Magliette/Maglietta("+beancart.getidArticolo()+")";
			   if(beancart.getSesso().equalsIgnoreCase("F")){
				   path=path+"F.jpg";
			   }
			   else{
				   path=path+".jpg";
			   }
		
      out.write("\r\n");
      out.write("\t\t<tr class=\"riga");
      out.print(k);
      out.write("\">\r\n");
      out.write("\t\t    <input type=\"hidden\" class=\"id\" value=\"");
      out.print(beancart.getidArticolo());
      out.write("\"/>\r\n");
      out.write("\t\t    <input type=\"hidden\" class=\"sex\" value=\"");
      out.print(beancart.getSesso());
      out.write("\"/>\r\n");
      out.write("\t\t    <input type=\"hidden\" class=\"tg1\" value=\"");
      out.print(beancart.getTaglia());
      out.write("\"/>\r\n");
      out.write("\t\t    <input type=\"hidden\" class=\"color\" value=\"");
      out.print(beancart.getColore());
      out.write("\"/>\r\n");
      out.write("\t\t\t<td class=\"colonna\"><div>");
      out.print(beancart.getnome());
      out.write("</div>\r\n");
      out.write("\t\t\t    <div><img class=\"maglietta\" src=");
      out.print(path);
      out.write("></div></td>\r\n");
      out.write("\t\t\t<td class=\"colonna\">");
      out.print(beancart.getColore());
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"colonna\"><select class=\"taglia\" id=\"");
      out.print(k);
      out.write("\">\r\n");
      out.write("                        ");
String tg="";
                           for(int i=0;i<8;i++){
                        	   switch(i){
                        	   case 0:tg="S";break;
                        	   case 1:tg="M";break;
                        	   case 2:tg="L";break;
                        	   case 3:tg="XL";break;
                        	   case 4:tg="XXL";break;
                        	   case 5:tg="3XL";break;
                        	   case 6:tg="4XL";break;
                        	   case 7:tg="5XL";break;
                        	   }
                               if(tg.equalsIgnoreCase(beancart.getTaglia())){
      out.write("\r\n");
      out.write("                               <option value=\"");
      out.print(tg);
      out.write("\" selected>");
      out.print(tg);
      out.write("</option>\r\n");
      out.write("                        ");
}
                               else{
                            	   
      out.write("\r\n");
      out.write("                               <option value=\"");
      out.print(tg);
      out.write('"');
      out.write('>');
      out.print(tg);
      out.write("</option>\r\n");
      out.write("                            \t   ");

                               }
                        }
      out.write("\r\n");
      out.write("                         </select>\r\n");
      out.write("                       </td>\r\n");
      out.write("\t\t\t<td class=\"colonna\">\r\n");
      out.write("\t\t\t    <select class=\"pezzi\" id=\"");
      out.print(k);
      out.write("\">\r\n");
      out.write("\t\t\t        ");
for(int i=1;i<=12;i++){ 
			              if(i==beancart.getquantita()){
      out.write("\r\n");
      out.write("\t\t\t              <option value=\"");
      out.print(beancart.getquantita());
      out.write("\" selected>");
      out.print(beancart.getquantita());
      out.write("</option>\r\n");
      out.write("\t\t\t             ");
}
			              else{
      out.write(" \r\n");
      out.write("\t\t\t              <option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>     \r\n");
      out.write("\t\t\t              ");
}
			             }
      out.write("\r\n");
      out.write("\t\t\t    </select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"colonna\" id=\"prezzo\">");
      out.print(beancart.getprezzo());
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"colonna\" id=\"rimozione\"><a href=\"./?action=deleteC&id=");
      out.print(beancart.getidArticolo());
      out.write("&sesso=");
      out.print(beancart.getSesso());
      out.write("&taglia=");
      out.print(beancart.getTaglia());
      out.write("&color=");
      out.print(beancart.getColore());
      out.write("\">Remove</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t</table>\t\t\r\n");
      out.write("\t");
 } 
      out.write("\t\r\n");
      out.write("\t<table id=\"subtotal\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t    <th class=\"subtotale-header\"> Subtotale </th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr id=\"prima-riga\">\r\n");
      out.write("\t<td><div class=\"label\">Costi di spedizione:</div>\r\n");
      out.write("\t<div class=\"labelfriend\">");
      out.print(cart.getShipmentString());
      out.write("</div>          </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr id=\"seconda-riga\">\r\n");
      out.write("\t<td><div class=\"label2\">Totale del tuo ordine:</div>\r\n");
      out.write("\t<div class=\"labelfriend2\">");
      out.print(x+",00 €");
      out.write("</div>          </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><div class=\"conferma\">Conferma il tuo ordine</div>        \r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td><img class=\"creditcard\" src=\"Immagini/CreditCard2.jpg\">        \r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<footer>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col1\">\r\n");
      out.write("\t\t\t\t\t<h2>I più venduti</h2>\r\n");
      out.write("\t\t\t\t<div class=\"menu-container\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"./?action=uomo\">T-Shirt Uomo</a></li>\r\n");
      out.write("                        <li><a href=\"./?action=donna\">T-Shirt Donna</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\t\t\t\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t<div class=\"col1\">\r\n");
      out.write("\t\t\t\t<h2>Info</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"menu-container\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"./About\">About</a></li>\r\n");
      out.write("                        <li><a href=\"./About\">Contattaci</a></li>\r\n");
      out.write("                        <li><a href=\"./Help\">Guida alle taglie</a></li>\r\n");
      out.write("                        <li><a href=\"./Help\">Tariffe Spedizione</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\t\t\t\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t<div class=\"col1\">\r\n");
      out.write("\t\t\t\t<h2>Segui</h2>\r\n");
      out.write("\t\t\t\t<div class=\"menu-container\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a target=\"_blank\" href=\"https://www.facebook.com/\">Facebook</a></li>\r\n");
      out.write("                        <li><a target=\"_blank\" href=\"https://twitter.com/\">Twitter</a></li>\r\n");
      out.write("                        <li><a target=\"_blank\" href=\"https://www.tumblr.com/\">Tumblr</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\t\t\t\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t<div class=\"col2\">\r\n");
      out.write("\t\t\t\t<div class=\"CreditCard\">\r\n");
      out.write("\t\t\t\t<img src=\"Immagini/CreditCard.png\">\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t© 2016 Core Shirt S.R.L | P. IVA 01594368721<br>\r\n");
      out.write("\t\t\t\t\t\tAll designs copyright by owner.<br>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">Privacy Policy</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
