/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2016-12-22 08:39:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import model.Articolo;
import model.Cart;

public final class Help_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Articolo");
    _jspx_imports_classes.add("model.Cart");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 
      Cart cart = (Cart) request.getAttribute("cart");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" lang=\"it\">\r\n");
      out.write("<head>\r\n");
      out.write("    <link rel=\"icon\" href=\"Immagini/sprite0.png\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/base.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/Help.css\" type=\"text/css\">\r\n");
      out.write("    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"Content-Language\" content=\"it-IT\" />\r\n");
      out.write("    <meta name=\"description\" content=\"Il miglior sito dove acquistare T-Shirt  per qualsiasi gusto e necessità, con un'ampia scelta di modelli aggiornati periodicamente con i migliori design della rete.\" />\r\n");
      out.write("    <meta name=\"keywords\" content=\"T-shirt, magliette, maglietta, nerd, cinema, divertenti, geek, core, series, best\" />\r\n");
      out.write("    <title>Help | Core Shirt: The Best T-Shirts series</title>\r\n");
      out.write("    \r\n");
      out.write("     </head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("    <article id=\"articolo1\">\r\n");
      out.write("    <div id=\"lista\">\r\n");
      out.write("    <a href=\"./\"><div id=\"banner\"> <img class=\"Banner\" src=\"Immagini/prova.png\"> \r\n");
      out.write("          <img class=\"core\" src=\"Immagini/core2.png\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    <div>\r\n");
      out.write("    <nav>    \r\n");
      out.write("        <ul id=\"menu\">\r\n");
      out.write("            <li><a href=\"./\"><img class=\"home\" src=\"Immagini/home.png\"></a> </li>\r\n");
      out.write("            <li><a href=\"./?action=Uomo\"> Uomo </a></li>\r\n");
      out.write("            <li><a href=\"./?action=Donna\"> Donna  </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"./About\">About</a></li>\r\n");
      out.write("            <li><a href=\"./Help\">Help</a></li>   \r\n");
      out.write("            <li><a href=\"./Checkout\">Checkout</a></li>\r\n");
      out.write("            <li><a href=\"./?action=cart\">\r\n");
      out.write("                <img class=\"cart\" src=\"Immagini/cart.png\"></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </article>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("<div class=\"help\">\r\n");
      out.write("        <h1 class=\"about\"> HELP </h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("            <div class=\"answers-column\">\r\n");
      out.write("                 <div class=\"answers\">\r\n");
      out.write("                     <div class=\"titolo\"><h4>Come funziona Core Shirt?</div></h4>\r\n");
      out.write("                     <p>Il concetto è semplice, su Core Shirt puoi acquistare le migliori T-shirt del web e non. A tua disposizione ci sono tantissimi design tra cui scegliere, tutti eccezionali, scegli il tuo preferito, aggiungilo al carrello, procedi con l'acquisto e in poco tempo avrai a casa tua una maglietta invidiabile.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"titolo\"><h4>Quante T-shirt posso ordinare con un solo acquisto?</div></h4>\r\n");
      out.write("                     <p>Il numero massimo di T-shirt ordinabili con un solo acquisto è di 12 pezzi.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                     \r\n");
      out.write("                      <div class=\"titolo\"><h4>Come vestono le vostre T-shirt?</div></h4>\r\n");
      out.write("                     <p>Alla perfezione!! A patto che si acquistino T-shirt con la giusta taglia.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                      <div class=\"titolo\"><h4>Come stampate le T-shirt?</div></h4>\r\n");
      out.write("                     <p>Serigrafia, lo standard industriale per creare eccellenti prodotti che durino nel tempo le cui grafiche non sbiadiscano dopo 48 ore.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"titolo\"><h4>Su che tipo di T-shirt stampate?</div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                     Tutte le t-shirt su cui stampiamo sono 100% cotone, e vestono alla perfezione!! O almeno, è ciò che speriamo.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"titolo\"><h4>Le t-shirt di Tee Tee si restringono?</div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                     Col passare del tempo, lavaggio dopo lavaggio, c'è un alto rischio che i tessuti si restringano. Una misura che va da 1 a 3 cm, tendenzialmente.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"titolo\"><h4>Come dovrei lavare le t-shirt per preservarle meglio?</div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                     Il nostro consiglio è di non lavare le t-shirt in acqua calda, e non farle asciugare nell'asciugatrice. Sempre meglio lavarle in acqua fredda (ancora meglio a mano, se vi va) e lasciarle asciugare in modo naturale.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                      <div class=\"titolo\"><h4>Sulla maglia c'è una sorta di alone bianco rettangolare, che è?</div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                     È l'alone che lascia la soluzione idrosolubile che dobbiamo necessariamente utilizzare per tenere le t-shirt “attaccate” alla macchina serigrafica per far sì che le stampe siano perfette. Un semplice lavaggio e l'alone sparisce!</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"titolo\"><h4>Che è la serigrafia? </div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                    Ah, i tecnicismi. Linkare una pagina di Wikipedia non è particolarmente brillante, ma <a href=\"https://it.wikipedia.org/wiki/Serigrafia\">qui</a> ci si può fare un'idea sul processo serigrafico in generale.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"titolo\"><h4>Che metodi di pagamento accettate??</div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                     Solo uno in verità: Paypal.\r\n");
      out.write("                     Se sei finito su questo sito probabilmente conosci già il servizio, ma forse non sai che Paypal è la piattaforma leader a livello mondiale per i pagamenti online.\r\n");
      out.write("                     Tutti i processi di pagamento passano attraverso Paypal.\r\n");
      out.write("                     Se hai un account sai già come funziona e non necessiti di spiegazioni, in caso contrario...</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"titolo\"><h4>Non ho un account Paypal. Posso pagare comunque?</div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                     Certo che sì.\r\n");
      out.write("                     In fase di checkout non devi far altro che selezionare l'opzione \"Non hai un conto Paypal?\".\r\n");
      out.write("                     Ti verrà così dato modo di pagare comunque, dal momento in cui sarà Paypal stesso ad occuparsi del processo pur non disponendo tu di un account.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"titolo\"><h4>Paypal accetta la Postepay e le prepagate in generale?</div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                     Sì.\r\n");
      out.write("                     Puoi tranquillamente utilizzare sia una carta di credito classica che una prepagata. Nessun problema, dunque, per pagare con Postepay/Prepagata Paypal o qualsiasi altra carta prepagata emessa dai vari istituti di credito.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"titolo\"><h4>Accettate contrassegno/pagamento alla consegna?</div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                     No, ci spiace :(</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"titolo\"><h4>Accettate bonifico bancario?</div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                     No, ci spiace :(</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"titolo\"><h4>Sono sicuri i pagamenti con Core Shirt?</div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                     Assolutamente.\r\n");
      out.write("                     Facciamo affidamento sui sistemi di Paypal, che è il marchio leader nel settore delle transazioni online. Tutto viene processato sui loro sistemi, ovviamente criptato secondo gli standard attualmente più sicuri.</p><br />\r\n");
      out.write("                         \r\n");
      out.write("                     <div class=\"titolo\"><h4>Con chi spedite?</div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                     Al momento, solo ed esclusivamente con Poste Italiane. Semplicemente riceverai la tua busta Tee Tee come ricevi la normale corrispondenza, consegnata dal postino di zona.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                      <div class=\"titolo\"><h4>Posso scegliere un corriere specifico?</div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                     No. Solo Poste Italiane per ora, non vi sono alternative.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"titolo\"><h4>A quanto ammontano le spese di spedizione?</div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                     Ovviamente tutto dipende da dove vivi, da quante t-shirt hai intenzione di comprare e da che metodo di spedizione intendi utilizzare.<br /><br />\r\n");
      out.write("\r\n");
      out.write("Qua sotto trovi una tabella riassuntiva dei costi di spedizione.<br /><br />\r\n");
      out.write("\r\n");
      out.write("ITALIA<br /><br />\r\n");
      out.write("\r\n");
      out.write("1 t-shirt Prioritaria (non assicurata in caso di smarrimento)<br /> 3.00€<br />\r\n");
      out.write("2 t-shirt Prioritaria (non assicurata in caso di smarrimento)<br /> 4.00€<br />\r\n");
      out.write("3 t-shirt Prioritaria (non assicurata in caso di smarrimento)<br /> NON DISPONIBILE<br />\r\n");
      out.write("1 t-shirt Raccomandata tracciabile<br />\r\n");
      out.write("5.00€<br />\r\n");
      out.write("2 t-shirt Raccomandata tracciabile<br />\r\n");
      out.write("5.50€<br />\r\n");
      out.write("3 t-shirt Raccomandata tracciabile<br />\r\n");
      out.write("5.50€<br />\r\n");
      out.write("1 felpa Raccomandata tracciabile<br />\r\n");
      out.write("5.50<br /><br />\r\n");
      out.write("                         \r\n");
      out.write("EUROPA, AFRICA DEL NORD<br /><br />\r\n");
      out.write("\r\n");
      out.write("1 t-shirt Prioritaria (non assicurata in caso di smarrimento)<br /> 3.00€<br />\r\n");
      out.write("2 t-shirt Prioritaria (non assicurata in caso di smarrimento)<br /> 5.5€<br />\r\n");
      out.write("3 t-shirt Prioritaria (non assicurata in caso di smarrimento)<br /> 6.00€<br />\r\n");
      out.write("1 t-shirt Raccomandata<br />\r\n");
      out.write("9.00€<br />\r\n");
      out.write("2 t-shirt Raccomandata<br />\r\n");
      out.write("10.50€<br />\r\n");
      out.write("3 t-shirt Raccomandata<br />\r\n");
      out.write("12.00€<br />\r\n");
      out.write("1 felpa Raccomandata tracciabile<br />\r\n");
      out.write("12.00€<br />\r\n");
      out.write("1 felpa e 1 t-shirt Raccomandata tracciabile<br />\r\n");
      out.write("12.00€<br /><br />\r\n");
      out.write("\r\n");
      out.write("NORD AMERICA, SUD AMERICA, ASIA<br /><br />\r\n");
      out.write("\r\n");
      out.write("1 t-shirt Prioritaria (non assicurata in caso di smarrimento)<br /> 4.50€<br />\r\n");
      out.write("2 t-shirt Prioritaria (non assicurata in caso di smarrimento)<br />8.50€<br />\r\n");
      out.write("3 t-shirt Prioritaria (non assicurata in caso di smarrimento)<br /> 9.00€<br />\r\n");
      out.write("1 t-shirt Raccomandata tracciabile<br />\r\n");
      out.write("10.00€<br />\r\n");
      out.write("2 t-shirt Raccomandata tracciabile<br />\r\n");
      out.write("13.50€<br />\r\n");
      out.write("3 t-shirt Raccomandata tracciabile<br />\r\n");
      out.write("15.50€<br />\r\n");
      out.write("1 felpa Raccomandata tracciabile<br />\r\n");
      out.write("15.50€<br />\r\n");
      out.write("1 felpa e 1 t-shirt Raccomandata tracciabile<br />\r\n");
      out.write("15.50€<br /><br />\r\n");
      out.write("\r\n");
      out.write("OCEANIA<br /><br />\r\n");
      out.write("\r\n");
      out.write("1 t-shirt Prioritaria (non assicurata in caso di smarrimento)<br /> 6.50€<br />\r\n");
      out.write("2 t-shirt Prioritaria (non assicurata in caso di smarrimento)<br /> 11.00€<br />\r\n");
      out.write("3 t-shirt Prioritaria (non assicurata in caso di smarrimento)<br /> 12.00€<br />\r\n");
      out.write("1 t-shirt Raccomandata tracciabile<br /> \r\n");
      out.write("11.50€<br />\r\n");
      out.write("2 t-shirt Raccomandata tracciabile<br /> \r\n");
      out.write("15.00€<br />\r\n");
      out.write("3 t-shirt Raccomandata tracciabile<br />\r\n");
      out.write("20.00€<br />\r\n");
      out.write("1 felpa Raccomandata tracciabile<br /> \r\n");
      out.write("20.00€<br />\r\n");
      out.write("1 felpa e 1 t-shirt Raccomandata tracciabile 20.00€<br />\r\n");
      out.write("</p><br />\r\n");
      out.write("\r\n");
      out.write("                     <div class=\"titolo\"><h4>Quanto ci vorrà prima di ricevere il mio ordine?</div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                     I tempi possono variare parecchio da paese a paese, anche in base al tipo di spedizione scelto.\r\n");
      out.write("\r\n");
      out.write("Ci piacerebbe dire che tutte le t-shirt sono già stampate e pronte per essere spedite o che abbiamo un servizio CoreShirtSuperSpedizioneUltraPlus che ve le farà avere il giorno dopo magari gratis. Purtroppo la realtà dei fatti è ben diversa.<br />\r\n");
      out.write("Le t-shirt vengono stampate soltanto una volta ogni 2 giorni. Ciò significa che le avremo fisicamente in mano non prima di 3 giorni successivi all'acquisto.<br />\r\n");
      out.write("\r\n");
      out.write("In quel momento le spediremo.<br />\r\n");
      out.write("\r\n");
      out.write("Partendo quindi dal presupposto che ci vogliono SEMPRE 3 giorni lavorativi prima che le t-shirt abbiano preso vita, questi sono i tempi di spedizione:<br /><br />\r\n");
      out.write("\r\n");
      out.write("Italia:<br /><br />\r\n");
      out.write("\r\n");
      out.write("- Prioritaria, non tracciabile (non assicurata in caso di smarrimento): 3 + 2/12 = 5/15 giorni lavorativi.<br />\r\n");
      out.write("\r\n");
      out.write("- Raccomandata, tracciabile: 3 + 3/8 = 9/11 giorni lavorativi.<br /><br />\r\n");
      out.write("\r\n");
      out.write("Europa, Africa del Nord:<br /><br />\r\n");
      out.write("\r\n");
      out.write("- Prioritaria, non tracciabile (non assicurata in caso di smarrimento): 3 + 3/17 = 9/20 giorni lavorativi.<br />\r\n");
      out.write("\r\n");
      out.write("- Raccomandata, tracciabile: 3 + 6/12 = 12/18 giorni lavorativi.<br /><br />\r\n");
      out.write("\r\n");
      out.write("Nord America:<br /><br />\r\n");
      out.write("\r\n");
      out.write("- Prioritaria, non tracciabile (non assicurata in caso di smarrimento): 3 + 6/27 = 12/30 giorni lavorativi.<br />\r\n");
      out.write("\r\n");
      out.write("- Raccomandata, tracciabile: 3 + 14/27 = 20/30 giorni lavorativi.<br /><br />\r\n");
      out.write("\r\n");
      out.write("Sud America, Asia, Oceania:<br /><br />\r\n");
      out.write("\r\n");
      out.write("- Prioritaria, non tracciabile (non assicurata in caso di smarrimento): 3 + 8/27 = 14/30 giorni lavorativi.<br />\r\n");
      out.write("\r\n");
      out.write("- Raccomandata, tracciabile: 3 + 17/27 = 23/30 giorni lavorativi.<br /><br />\r\n");
      out.write("\r\n");
      out.write("                         \r\n");
      out.write("                     <div class=\"titolo\"><h4>Se la mia spedizione va persa?</div></h4>\r\n");
      out.write("                     <p>\r\n");
      out.write("                     Speriamo ciò non accada mai.<br /><br />\r\n");
      out.write("\r\n");
      out.write("Ma nel caso, tutto dipende dal metodo di spedizione scelto in fase di ordinazione:<br /><br />\r\n");
      out.write("\r\n");
      out.write("- se avevi scelto una spedizione non tracciabile e quindi non assicurata in caso di smarrimento, non potremo fare nulla. Brutto da scrivere, ma non possiamo addossarci rischi del genere.<br />\r\n");
      out.write("<br />\r\n");
      out.write("- se avevi scelto una spedizione tracciabile e quindi assicurata in caso di smarrimento, potrai scegliere fra un rimborso completo oppure la spedizione di un'altra t-shirt, che potrà essere sia la stessa che avevi acquistato precedentemente o un'altra tra le tante disponibili, ed ovviamente te la spediremo gratuitamente.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                    <div class=\"titolo\"><h4>Spedite nel mio paese?</div></h4>\r\n");
      out.write("                    <p>\r\n");
      out.write("                    Sure!!! :D<br /><br />\r\n");
      out.write("                    Spediamo in ogni angolo del globo.<br /><br />\r\n");
      out.write("\r\n");
      out.write("                    Alcuni paesi, tuttavia, hanno delle restrizioni, in quel caso verrai contattato e cercheremo di risolvere il problema il prima possibile e nel migliore dei modi.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                    <div class=\"titolo\"><h4>Posso tracciare il mio ordine?</div></h4>\r\n");
      out.write("                    <p>\r\n");
      out.write("                    Se vivi in Italia e hai scelto la spedizione Raccomandata, sì.<br /><br />\r\n");
      out.write("                    Ti invieremo il numero di tracking e il link presso cui effettuarlo.<br /><br />\r\n");
      out.write("\r\n");
      out.write("                    Se vivi all'estero, purtroppo non del tutto.\r\n");
      out.write("                    Ti avviseremo quando verrà inviata la t-shirt e ti invieremo il numero di tracking, ma non tutti i servizi postali nazionali esteri tracciano le Raccomandate provenienti dagli altri paesi.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                    <div class=\"titolo\"><h4>Posso aggiungere articoli ad un ordine già concluso?</div></h4>\r\n");
      out.write("                    <p>\r\n");
      out.write("                    No, in nessun caso, ci spiace :(</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                    <div class=\"titolo\"><h4>Posso modificare un ordine già concluso?</div></h4>\r\n");
      out.write("                    <p>\r\n");
      out.write("                    Se si tratta di un cambio di taglia, cercheremo di fare del nostro meglio per venirti incontro.<br /><br />\r\n");
      out.write("                    Dovrai però assolutamente contattarci DURANTE il giorno stesso dell'ordine ed assolutamente ENTRO le 17 e non dopo.\r\n");
      out.write("                    In ogni caso, purtroppo, non assicuriamo di essere in grado di intervenire.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                    <div class=\"titolo\"><h4>Come vi posso contattare?</div></h4>\r\n");
      out.write("                    <p>\r\n");
      out.write("                    Per qualsivoglia chiarimento, problema, suggerimento se non addirittura complimento (non è brutto che le persone si facciano sentire solo quando insorgono problemi? accettiamo anche le buone parole, se meritate si intende! :D ) tutto quel che devi fare è andare sulla nostra pagina ABOUT (linkata in ogni pagina del sito, in basso).<br /><br />\r\n");
      out.write("                    Cerchiamo di essere il più veloci possibile nel rispondere e diamo la precedenza a chi si comporta educatamente.</p><br />\r\n");
      out.write("                     \r\n");
      out.write("                    <div class=\"titolo\"><h4>Il mio ordine è partito ma non è ancora arrivato. Cosa dovrei fare?</div></h4>\r\n");
      out.write("                    <p>\r\n");
      out.write("                   Se non sono ancora passati tutti i giorni (lavorativi) entro i quali dovresti aver ricevuto la tua t-shirt, aspetta.<br /><br /> Potrebbe arrivare esattamente l'ultimo giorno!<br /><br />\r\n");
      out.write("                   Se invece non hai ancora ricevuto nulla e il numero di giorni massimo è passato, contattaci.\r\n");
      out.write("                   Cercheremo di capire cosa è andato storto e di farti arrivare la t-shirt il più presto possibile, se fattibile.<br /><br />\r\n");
      out.write("                   Ti ricordiamo che se scegli un tipo di spedizione non tracciato non potremo rimborsarti o spedirti un'altra t-shirt (e ce ne scusiamo), mentre se opti per una spedizione tracciabile ti rimborseremo o spediremo un'altra T-shirt.</p><br />\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col1\">\r\n");
      out.write("\t\t\t\t\t<h2>I più venduti</h2>\r\n");
      out.write("\t\t\t\t<div class=\"menu-container\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"./?action=uomo\">T-Shirt Uomo</a></li>\r\n");
      out.write("                        <li><a href=\"./?action=donna\">T-Shirt Donna</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\t\t\t\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t<div class=\"col1\">\r\n");
      out.write("\t\t\t\t<h2>Info</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"menu-container\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"./About\">About</a></li>\r\n");
      out.write("                        <li><a href=\"./About\">Contattaci</a></li>\r\n");
      out.write("                        <li><a href=\"./Help\">Guida alle taglie</a></li>\r\n");
      out.write("                        <li><a href=\"./Help\">Tariffe Spedizione</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\t\t\t\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t<div class=\"col1\">\r\n");
      out.write("\t\t\t\t<h2>Segui</h2>\r\n");
      out.write("\t\t\t\t<div class=\"menu-container\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a target=\"_blank\" href=\"https://www.facebook.com/\">Facebook</a></li>\r\n");
      out.write("                        <li><a target=\"_blank\" href=\"https://twitter.com/\">Twitter</a></li>\r\n");
      out.write("                        <li><a target=\"_blank\" href=\"https://www.tumblr.com/\">Tumblr</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\t\t\t\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t<div class=\"col2\">\r\n");
      out.write("\t\t\t\t<div class=\"CreditCard\">\r\n");
      out.write("\t\t\t\t<img src=\"Immagini/CreditCard.png\">\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t© 2016 Core Shirt S.R.L | P. IVA 01594368721<br>\r\n");
      out.write("\t\t\t\t\t\tAll designs copyright by owner.<br>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">Privacy Policy</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
