/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2016-12-22 14:42:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import model.Dipendente;
import control.ManageDipendente;
import control.DbConnect;

public final class inserisciDipendente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


ManageDipendente md=new ManageDipendente();
ArrayList<Dipendente> dipendenti=md.getDipendenti(); 

Dipendente d;
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Dipendente");
    _jspx_imports_classes.add("control.DbConnect");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("control.ManageDipendente");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Prova</title>\r\n");
      out.write("<script src=\"checkForm.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"checkForm.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3>Inserisci Dipendente</h3>\r\n");
      out.write("<form name=\"InsertDipendente\" action=\"ServletDipendente\" method=\"post\" onsubmit=\"return validateForm()\">\r\n");
      out.write("\tid Dipendente<br>\r\n");
      out.write("\t<input type=\"text\" name=\"idDipendente\"><br>\r\n");
      out.write("\tNome<br>\r\n");
      out.write("\t<input type=\"text\" name=\"nome\"><br>\r\n");
      out.write("\tCognome<br>\r\n");
      out.write("\t<input type=\"text\" name=\"cognome\"><br>\r\n");
      out.write("\tCodice Fiscale <br>\r\n");
      out.write("\t<input type=\"text\" name=\"codiceFiscale\"><br>\r\n");
      out.write("\tStipendio <br>\r\n");
      out.write("\t<input type=\"text\" name=\"stipendio\"><br>\r\n");
      out.write("\tTipo<br>\r\n");
      out.write("\t<input type=\"text\" name=\"tipo\"><br>\r\n");
      out.write("\tUsername<br>\r\n");
      out.write("\t<input type=\"text\" name=\"username\"><br>\r\n");
      out.write("\tPassword<br>\r\n");
      out.write("\t<input type=\"text\" name=\"password\"><br>\r\n");
      out.write("\t<br><button type=\"submit\" onclick=\"ServletDipendente\" onsubmit=\"return validateForm()\">Inserisci</button>\r\n");
      out.write("</form>\r\n");
      out.write("<br>\r\n");
      out.write("<h3>Rimuovi Dipendente</h3><br>\r\n");
      out.write("\r\n");
      out.write("<form  action=\"ServletDipendente\" method=\"post\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<select name=\"DeleteDipendente\">\r\n");
      out.write("\t ");

	 	for(int i=0;i<dipendenti.size();i++){
      out.write("\r\n");
      out.write("\t \t\t<option value=\"");
      out.print(dipendenti.get(i).getId());
      out.write("\" selected>");
      out.print(dipendenti.get(i).getNome()+" "+dipendenti.get(i).getCognome());
      out.write("</option>\r\n");
      out.write("\t \t\t");
d=dipendenti.get(i);
      out.write("\r\n");
      out.write("\t \t");
 }
      out.write("\r\n");
      out.write("\t</select> <button type=\"submit\" onclick=\"ServletDipendente\">Rimuovi</button><br><br>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<form action=\"ServletDipendente\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"id\" name=\"modificaId\" value=\"");
      out.print(d.getId());
      out.write("\">\r\n");
      out.write("\tNome <input type=\"text\" name=\"modificaNome\" value=\"");
      out.print(d.getNome());
      out.write("\"><br><br>\r\n");
      out.write("\tCognome <input type=\"text\" name=\"modificaCognome\" value=\"");
      out.print(d.getCognome());
      out.write("\"><br><br>\r\n");
      out.write("\tCf <input type=\"text\" name=\"modificaCf\" value=\"");
      out.print(d.getCodiceFiscale());
      out.write("\"><br><br>\r\n");
      out.write("\tStipendio <input type=\"text\" name=\"modificaStipendio\" value=\"");
      out.print(d.getStipendio());
      out.write("\"><br><br>\r\n");
      out.write("\tTipo <input type=\"text\" name=\"modificaTipo\" value=\"");
      out.print(d.getTipo());
      out.write('"');
      out.write('>');
d.getTipo();
      out.write("<br><br>\r\n");
      out.write("\tUsername <input type=\"text\" name=\"modificaUsername\" value=\"");
      out.print(d.getUsername());
      out.write('"');
      out.write('>');
d.getUsername();
      out.write("<br><br>\r\n");
      out.write("\tPassword <input type=\"text\" name=\"modificaPassword\" value=\"");
      out.print(d.getPassword());
      out.write('"');
      out.write('>');
d.getPassword();
      out.write("<br><br>\r\n");
      out.write("\t <button type=\"submit\" onclick=\"ServletDipendente\">Modifica</button>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
