/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2016-12-25 16:07:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import model.Dipendente;
import control.ManageDipendente;
import control.DbConnect;
import java.sql.*;

public final class prova_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Dipendente");
    _jspx_imports_classes.add("control.DbConnect");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("control.ManageDipendente");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Prova Ajax</title>\r\n");
      out.write("<script src=\"ajaxs.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form name=\"manageDipendente\" >\r\n");
      out.write("<select name=\"idDipendente\">\r\n");

	ManageDipendente md=new ManageDipendente();
	ArrayList<Dipendente> dipendenti=md.getDipendenti();

for(int i=0;i<dipendenti.size();i++){ 
      out.write("\r\n");
      out.write("\t<option value=\"");
      out.print(dipendenti.get(i).getId());
      out.write('"');
      out.write('>');
      out.print(dipendenti.get(i).getId());
      out.write("</option>\r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("</select><input type=\"submit\" onclick=\"postComment()\"><br><br>\r\n");
      out.write("</form>\r\n");
      out.write("<form action=\"GestisciDipendente\" method=\"post\">\r\n");

	String id=request.getParameter("idDipendente");
	if(id=="" || id==null)
		out.print("<b>inserisci id</b>");
	else{
		try{
			Class.forName("com.mysql.jdbc.Driver");
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/coreshirt","root","kalibandulu");
			PreparedStatement ps=con.prepareStatement("select * from dipendente where idDipendente=?");
			ps.setInt(1,Integer.parseInt(id));
			ResultSet rs=ps.executeQuery();
			while(rs.next()){
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print(rs.getInt("idDipendente"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tNome<input type=\"text\" name=\"nome\" value=\"");
      out.print(rs.getString("nome"));
      out.write("\"><br><br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tCognome<input type=\"text\" name=\"cognome\" value=\"");
      out.print(rs.getString("cognome"));
      out.write("\"><br><br>\r\n");
      out.write("\t\t\t\tCodF<input type=\"text\" name=\"cf\" value=\"");
      out.print(rs.getString("codicefiscale"));
      out.write("\"><br><br>\r\n");
      out.write("\t\t\t\tStipendio<input type=\"text\" name=\"stipendio\" value=\"");
      out.print(rs.getString("stipendio"));
      out.write("\"><br><br>\r\n");
      out.write("\t\t\t\tTipo<input type=\"text\" name=\"tipo\" value=\"");
      out.print(rs.getString("tipo"));
      out.write("\"><br><br>\r\n");
      out.write("\t\t\t\tUsername<input type=\"text\" name=\"username\" value=\"");
      out.print(rs.getString("username"));
      out.write("\"><br><br>\r\n");
      out.write("\t\t\t\tPassword<input type=\"text\" name=\"password\" value=\"");
      out.print(rs.getString("password"));
      out.write("\"><br><br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");
 }catch(Exception e){
			out.print(e);
		}
	}

      out.write("\r\n");
      out.write("<input type=\"submit\" onclick=\"GestisciDipendente\">\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
